/**
 * Hydrogen Integration API
 * The Hydrogen Integration API
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InvoicePayment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InvoicePayment'));
  } else {
    // Browser globals (root is window)
    if (!root.HydrogenIntegrationApi) {
      root.HydrogenIntegrationApi = {};
    }
    root.HydrogenIntegrationApi.AccountingInvoicePaymentResponseVO = factory(root.HydrogenIntegrationApi.ApiClient, root.HydrogenIntegrationApi.InvoicePayment);
  }
}(this, function(ApiClient, InvoicePayment) {
  'use strict';




  /**
   * The AccountingInvoicePaymentResponseVO model module.
   * @module model/AccountingInvoicePaymentResponseVO
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>AccountingInvoicePaymentResponseVO</code>.
   * @alias module:model/AccountingInvoicePaymentResponseVO
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>AccountingInvoicePaymentResponseVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountingInvoicePaymentResponseVO} obj Optional instance to populate.
   * @return {module:model/AccountingInvoicePaymentResponseVO} The populated <code>AccountingInvoicePaymentResponseVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('body')) {
        obj['body'] = InvoicePayment.constructFromObject(data['body']);
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('status_code')) {
        obj['status_code'] = ApiClient.convertToType(data['status_code'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InvoicePayment} body
   */
  exports.prototype['body'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {Number} status_code
   */
  exports.prototype['status_code'] = undefined;



  return exports;
}));


