/*
 * Hydrogen Integration API
 * The Hydrogen Integration API
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AggregationAccountTransaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AggregationAccountTransaction'));
  } else {
    // Browser globals (root is window)
    if (!root.HydrogenIntegrationApi) {
      root.HydrogenIntegrationApi = {};
    }
    root.HydrogenIntegrationApi.AggregationAccountTransactionResponseInternalObjectVO = factory(root.HydrogenIntegrationApi.ApiClient, root.HydrogenIntegrationApi.AggregationAccountTransaction);
  }
}(this, function(ApiClient, AggregationAccountTransaction) {
  'use strict';

  /**
   * The AggregationAccountTransactionResponseInternalObjectVO model module.
   * @module model/AggregationAccountTransactionResponseInternalObjectVO
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>AggregationAccountTransactionResponseInternalObjectVO</code>.
   * @alias module:model/AggregationAccountTransactionResponseInternalObjectVO
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AggregationAccountTransactionResponseInternalObjectVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AggregationAccountTransactionResponseInternalObjectVO} obj Optional instance to populate.
   * @return {module:model/AggregationAccountTransactionResponseInternalObjectVO} The populated <code>AggregationAccountTransactionResponseInternalObjectVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('body'))
        obj.body = AggregationAccountTransaction.constructFromObject(data['body']);
      if (data.hasOwnProperty('status_code'))
        obj.statusCode = ApiClient.convertToType(data['status_code'], 'Number');
    }
    return obj;
  }

  /**
   * @member {module:model/AggregationAccountTransaction} body
   */
  exports.prototype.body = undefined;

  /**
   * @member {Number} statusCode
   */
  exports.prototype.statusCode = undefined;

  return exports;

}));
