/*
 * Hydrogen Integration API
 * The Hydrogen Integration API
 *
 * OpenAPI spec version: 1.2.1
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IavTokenExchangeVendorResponseVO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IavTokenExchangeVendorResponseVO'));
  } else {
    // Browser globals (root is window)
    if (!root.HydrogenIntegrationApi) {
      root.HydrogenIntegrationApi = {};
    }
    root.HydrogenIntegrationApi.ExchangePublicTokenVO = factory(root.HydrogenIntegrationApi.ApiClient, root.HydrogenIntegrationApi.IavTokenExchangeVendorResponseVO);
  }
}(this, function(ApiClient, IavTokenExchangeVendorResponseVO) {
  'use strict';

  /**
   * The ExchangePublicTokenVO model module.
   * @module model/ExchangePublicTokenVO
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>ExchangePublicTokenVO</code>.
   * @alias module:model/ExchangePublicTokenVO
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ExchangePublicTokenVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExchangePublicTokenVO} obj Optional instance to populate.
   * @return {module:model/ExchangePublicTokenVO} The populated <code>ExchangePublicTokenVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('integration_type'))
        obj.integrationType = ApiClient.convertToType(data['integration_type'], 'String');
      if (data.hasOwnProperty('nucleus_client_id'))
        obj.nucleusClientId = ApiClient.convertToType(data['nucleus_client_id'], 'String');
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], 'String');
      if (data.hasOwnProperty('vendor_name'))
        obj.vendorName = ApiClient.convertToType(data['vendor_name'], 'String');
      if (data.hasOwnProperty('vendor_response'))
        obj.vendorResponse = IavTokenExchangeVendorResponseVO.constructFromObject(data['vendor_response']);
    }
    return obj;
  }

  /**
   * @member {String} integrationType
   */
  exports.prototype.integrationType = undefined;

  /**
   * @member {String} nucleusClientId
   */
  exports.prototype.nucleusClientId = undefined;

  /**
   * @member {String} product
   */
  exports.prototype.product = undefined;

  /**
   * @member {String} vendorName
   */
  exports.prototype.vendorName = undefined;

  /**
   * @member {module:model/IavTokenExchangeVendorResponseVO} vendorResponse
   */
  exports.prototype.vendorResponse = undefined;


  return exports;

}));
