# coding: utf-8

"""
    Molecule API Documentation

    The Hydrogen Molecule API  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: info@hydrogenplatform.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import molecule_api
from molecule_api.api.wallet_api import WalletApi  # noqa: E501
from molecule_api.rest import ApiException


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self):
        self.api = molecule_api.api.wallet_api.WalletApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_wallet_using_post(self):
        """Test case for create_wallet_using_post

        Creates a new Wallet  # noqa: E501
        """
        pass

    def test_get_wallet_all_using_get(self):
        """Test case for get_wallet_all_using_get

        Fetch Wallet list  # noqa: E501
        """
        pass

    def test_get_wallet_by_wallet_key_using_get(self):
        """Test case for get_wallet_by_wallet_key_using_get

        Fetch Wallet details by Wallet Key ID  # noqa: E501
        """
        pass

    def test_get_wallet_using_get(self):
        """Test case for get_wallet_using_get

        Fetch Wallet details  # noqa: E501
        """
        pass

    def test_update_wallet_using_put(self):
        """Test case for update_wallet_using_put

        Update Wallet details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
