/*
 * Hydrogen Atom API
 * The Hydrogen Atom API
 *
 * OpenAPI spec version: 1.7.0
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hydrogen.nucleus.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * ClientAdvisorOverviewVO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-04T05:11:20.520Z")
public class ClientAdvisorOverviewVO {
  @SerializedName("age")
  private Integer age = null;

  @SerializedName("client_account_list")
  private List<ClientAccountAdvisorVO> clientAccountList = null;

  @SerializedName("client_assets")
  private ClientAssetsAdvisorVO clientAssets = null;

  @SerializedName("client_id")
  private UUID clientId = null;

  @SerializedName("date_of_birth")
  private OffsetDateTime dateOfBirth = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("gender")
  private String gender = null;

  @SerializedName("income")
  private Integer income = null;

  @SerializedName("last_name")
  private String lastName = null;

  public ClientAdvisorOverviewVO age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @ApiModelProperty(value = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public ClientAdvisorOverviewVO clientAccountList(List<ClientAccountAdvisorVO> clientAccountList) {
    this.clientAccountList = clientAccountList;
    return this;
  }

  public ClientAdvisorOverviewVO addClientAccountListItem(ClientAccountAdvisorVO clientAccountListItem) {
    if (this.clientAccountList == null) {
      this.clientAccountList = new ArrayList<ClientAccountAdvisorVO>();
    }
    this.clientAccountList.add(clientAccountListItem);
    return this;
  }

   /**
   * Get clientAccountList
   * @return clientAccountList
  **/
  @ApiModelProperty(value = "")
  public List<ClientAccountAdvisorVO> getClientAccountList() {
    return clientAccountList;
  }

  public void setClientAccountList(List<ClientAccountAdvisorVO> clientAccountList) {
    this.clientAccountList = clientAccountList;
  }

  public ClientAdvisorOverviewVO clientAssets(ClientAssetsAdvisorVO clientAssets) {
    this.clientAssets = clientAssets;
    return this;
  }

   /**
   * Get clientAssets
   * @return clientAssets
  **/
  @ApiModelProperty(value = "")
  public ClientAssetsAdvisorVO getClientAssets() {
    return clientAssets;
  }

  public void setClientAssets(ClientAssetsAdvisorVO clientAssets) {
    this.clientAssets = clientAssets;
  }

  public ClientAdvisorOverviewVO clientId(UUID clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public UUID getClientId() {
    return clientId;
  }

  public void setClientId(UUID clientId) {
    this.clientId = clientId;
  }

  public ClientAdvisorOverviewVO dateOfBirth(OffsetDateTime dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(OffsetDateTime dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public ClientAdvisorOverviewVO firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ClientAdvisorOverviewVO gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public ClientAdvisorOverviewVO income(Integer income) {
    this.income = income;
    return this;
  }

   /**
   * Get income
   * @return income
  **/
  @ApiModelProperty(value = "")
  public Integer getIncome() {
    return income;
  }

  public void setIncome(Integer income) {
    this.income = income;
  }

  public ClientAdvisorOverviewVO lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientAdvisorOverviewVO clientAdvisorOverviewVO = (ClientAdvisorOverviewVO) o;
    return Objects.equals(this.age, clientAdvisorOverviewVO.age) &&
        Objects.equals(this.clientAccountList, clientAdvisorOverviewVO.clientAccountList) &&
        Objects.equals(this.clientAssets, clientAdvisorOverviewVO.clientAssets) &&
        Objects.equals(this.clientId, clientAdvisorOverviewVO.clientId) &&
        Objects.equals(this.dateOfBirth, clientAdvisorOverviewVO.dateOfBirth) &&
        Objects.equals(this.firstName, clientAdvisorOverviewVO.firstName) &&
        Objects.equals(this.gender, clientAdvisorOverviewVO.gender) &&
        Objects.equals(this.income, clientAdvisorOverviewVO.income) &&
        Objects.equals(this.lastName, clientAdvisorOverviewVO.lastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(age, clientAccountList, clientAssets, clientId, dateOfBirth, firstName, gender, income, lastName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientAdvisorOverviewVO {\n");
    
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    clientAccountList: ").append(toIndentedString(clientAccountList)).append("\n");
    sb.append("    clientAssets: ").append(toIndentedString(clientAssets)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

