/* 
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * OpenAPI spec version: 1.9.4
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Nucleus.Api;
using Nucleus.ModelEntity;
using Nucleus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Nucleus.Test
{
    /// <summary>
    ///  Class for testing ClientCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientCredentialsTests
    {
        // TODO uncomment below to declare an instance variable for ClientCredentials
        //private ClientCredentials instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientCredentials
            //instance = new ClientCredentials();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientCredentials
        /// </summary>
        [Test]
        public void ClientCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClientCredentials
            //Assert.IsInstanceOfType<ClientCredentials> (instance, "variable 'instance' is a ClientCredentials");
        }


        /// <summary>
        /// Test the property 'CurrentPassword'
        /// </summary>
        [Test]
        public void CurrentPasswordTest()
        {
            // TODO unit test for the property 'CurrentPassword'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
