/* 
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * OpenAPI spec version: 1.9.4
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Nucleus.Api;
using Nucleus.ModelEntity;
using Nucleus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Nucleus.Test
{
    /// <summary>
    ///  Class for testing ReasonCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReasonCodeTests
    {
        // TODO uncomment below to declare an instance variable for ReasonCode
        //private ReasonCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReasonCode
            //instance = new ReasonCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReasonCode
        /// </summary>
        [Test]
        public void ReasonCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReasonCode
            //Assert.IsInstanceOfType<ReasonCode> (instance, "variable 'instance' is a ReasonCode");
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Test]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property '_ReasonCode'
        /// </summary>
        [Test]
        public void _ReasonCodeTest()
        {
            // TODO unit test for the property '_ReasonCode'
        }
        /// <summary>
        /// Test the property 'ReasonCodeDescription'
        /// </summary>
        [Test]
        public void ReasonCodeDescriptionTest()
        {
            // TODO unit test for the property 'ReasonCodeDescription'
        }
        /// <summary>
        /// Test the property 'ReasonType'
        /// </summary>
        [Test]
        public void ReasonTypeTest()
        {
            // TODO unit test for the property 'ReasonType'
        }
        /// <summary>
        /// Test the property 'SecondaryId'
        /// </summary>
        [Test]
        public void SecondaryIdTest()
        {
            // TODO unit test for the property 'SecondaryId'
        }
        /// <summary>
        /// Test the property 'Subcategory'
        /// </summary>
        [Test]
        public void SubcategoryTest()
        {
            // TODO unit test for the property 'Subcategory'
        }
        /// <summary>
        /// Test the property 'UpdateDate'
        /// </summary>
        [Test]
        public void UpdateDateTest()
        {
            // TODO unit test for the property 'UpdateDate'
        }

    }

}
