/*
 * Hydrogen Atom API
 * The Hydrogen Atom API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EducationCalculatorReturnDetail;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * EducationCalculatorAnnualcostResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-08T13:59:38.361-04:00")
public class EducationCalculatorAnnualcostResponse {
  @SerializedName("total_annual_cost")
  private BigDecimal totalAnnualCost = null;

  @SerializedName("total_cost")
  private BigDecimal totalCost = null;

  @SerializedName("return_details")
  private Map<String, EducationCalculatorReturnDetail> returnDetails = new HashMap<String, EducationCalculatorReturnDetail>();

  public EducationCalculatorAnnualcostResponse totalAnnualCost(BigDecimal totalAnnualCost) {
    this.totalAnnualCost = totalAnnualCost;
    return this;
  }

   /**
   * The total education cost per year that can be afforded, represented in today’s dollars.
   * minimum: 0
   * @return totalAnnualCost
  **/
  @ApiModelProperty(required = true, value = "The total education cost per year that can be afforded, represented in today’s dollars.")
  public BigDecimal getTotalAnnualCost() {
    return totalAnnualCost;
  }

  public void setTotalAnnualCost(BigDecimal totalAnnualCost) {
    this.totalAnnualCost = totalAnnualCost;
  }

  public EducationCalculatorAnnualcostResponse totalCost(BigDecimal totalCost) {
    this.totalCost = totalCost;
    return this;
  }

   /**
   * The total cost of education over the decumulation horizon, represented in future dollars.
   * minimum: 0
   * @return totalCost
  **/
  @ApiModelProperty(required = true, value = "The total cost of education over the decumulation horizon, represented in future dollars.")
  public BigDecimal getTotalCost() {
    return totalCost;
  }

  public void setTotalCost(BigDecimal totalCost) {
    this.totalCost = totalCost;
  }

  public EducationCalculatorAnnualcostResponse returnDetails(Map<String, EducationCalculatorReturnDetail> returnDetails) {
    this.returnDetails = returnDetails;
    return this;
  }

  public EducationCalculatorAnnualcostResponse putReturnDetailsItem(String key, EducationCalculatorReturnDetail returnDetailsItem) {
    this.returnDetails.put(key, returnDetailsItem);
    return this;
  }

   /**
   * Get returnDetails
   * @return returnDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public Map<String, EducationCalculatorReturnDetail> getReturnDetails() {
    return returnDetails;
  }

  public void setReturnDetails(Map<String, EducationCalculatorReturnDetail> returnDetails) {
    this.returnDetails = returnDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EducationCalculatorAnnualcostResponse educationCalculatorAnnualcostResponse = (EducationCalculatorAnnualcostResponse) o;
    return Objects.equals(this.totalAnnualCost, educationCalculatorAnnualcostResponse.totalAnnualCost) &&
        Objects.equals(this.totalCost, educationCalculatorAnnualcostResponse.totalCost) &&
        Objects.equals(this.returnDetails, educationCalculatorAnnualcostResponse.returnDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalAnnualCost, totalCost, returnDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EducationCalculatorAnnualcostResponse {\n");
    
    sb.append("    totalAnnualCost: ").append(toIndentedString(totalAnnualCost)).append("\n");
    sb.append("    totalCost: ").append(toIndentedString(totalCost)).append("\n");
    sb.append("    returnDetails: ").append(toIndentedString(returnDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

