/*
 * Hydrogen Atom API
 * The Hydrogen Atom API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HealthCheckResult;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * HealthCheckResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-08T13:59:38.361-04:00")
public class HealthCheckResponse {
  @SerializedName("liquidity_ratio_expenses")
  private HealthCheckResult liquidityRatioExpenses = null;

  @SerializedName("liquidity_ratio_liabilities")
  private HealthCheckResult liquidityRatioLiabilities = null;

  @SerializedName("current_ratio")
  private HealthCheckResult currentRatio = null;

  @SerializedName("asset_allocation_ratio")
  private HealthCheckResult assetAllocationRatio = null;

  @SerializedName("savings_ratio_gross")
  private HealthCheckResult savingsRatioGross = null;

  @SerializedName("savings_ratio_net")
  private HealthCheckResult savingsRatioNet = null;

  @SerializedName("total_assets")
  private BigDecimal totalAssets = null;

  @SerializedName("net_worth")
  private BigDecimal netWorth = null;

  @SerializedName("gross_monthly_income")
  private BigDecimal grossMonthlyIncome = null;

  @SerializedName("monthly_surplus")
  private BigDecimal monthlySurplus = null;

  public HealthCheckResponse liquidityRatioExpenses(HealthCheckResult liquidityRatioExpenses) {
    this.liquidityRatioExpenses = liquidityRatioExpenses;
    return this;
  }

   /**
   * Get liquidityRatioExpenses
   * @return liquidityRatioExpenses
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getLiquidityRatioExpenses() {
    return liquidityRatioExpenses;
  }

  public void setLiquidityRatioExpenses(HealthCheckResult liquidityRatioExpenses) {
    this.liquidityRatioExpenses = liquidityRatioExpenses;
  }

  public HealthCheckResponse liquidityRatioLiabilities(HealthCheckResult liquidityRatioLiabilities) {
    this.liquidityRatioLiabilities = liquidityRatioLiabilities;
    return this;
  }

   /**
   * Get liquidityRatioLiabilities
   * @return liquidityRatioLiabilities
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getLiquidityRatioLiabilities() {
    return liquidityRatioLiabilities;
  }

  public void setLiquidityRatioLiabilities(HealthCheckResult liquidityRatioLiabilities) {
    this.liquidityRatioLiabilities = liquidityRatioLiabilities;
  }

  public HealthCheckResponse currentRatio(HealthCheckResult currentRatio) {
    this.currentRatio = currentRatio;
    return this;
  }

   /**
   * Get currentRatio
   * @return currentRatio
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getCurrentRatio() {
    return currentRatio;
  }

  public void setCurrentRatio(HealthCheckResult currentRatio) {
    this.currentRatio = currentRatio;
  }

  public HealthCheckResponse assetAllocationRatio(HealthCheckResult assetAllocationRatio) {
    this.assetAllocationRatio = assetAllocationRatio;
    return this;
  }

   /**
   * Get assetAllocationRatio
   * @return assetAllocationRatio
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getAssetAllocationRatio() {
    return assetAllocationRatio;
  }

  public void setAssetAllocationRatio(HealthCheckResult assetAllocationRatio) {
    this.assetAllocationRatio = assetAllocationRatio;
  }

  public HealthCheckResponse savingsRatioGross(HealthCheckResult savingsRatioGross) {
    this.savingsRatioGross = savingsRatioGross;
    return this;
  }

   /**
   * Get savingsRatioGross
   * @return savingsRatioGross
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getSavingsRatioGross() {
    return savingsRatioGross;
  }

  public void setSavingsRatioGross(HealthCheckResult savingsRatioGross) {
    this.savingsRatioGross = savingsRatioGross;
  }

  public HealthCheckResponse savingsRatioNet(HealthCheckResult savingsRatioNet) {
    this.savingsRatioNet = savingsRatioNet;
    return this;
  }

   /**
   * Get savingsRatioNet
   * @return savingsRatioNet
  **/
  @ApiModelProperty(value = "")
  public HealthCheckResult getSavingsRatioNet() {
    return savingsRatioNet;
  }

  public void setSavingsRatioNet(HealthCheckResult savingsRatioNet) {
    this.savingsRatioNet = savingsRatioNet;
  }

  public HealthCheckResponse totalAssets(BigDecimal totalAssets) {
    this.totalAssets = totalAssets;
    return this;
  }

   /**
   * Total assets, calculated as liquid_assets + non_liquid_assets.
   * @return totalAssets
  **/
  @ApiModelProperty(value = "Total assets, calculated as liquid_assets + non_liquid_assets.")
  public BigDecimal getTotalAssets() {
    return totalAssets;
  }

  public void setTotalAssets(BigDecimal totalAssets) {
    this.totalAssets = totalAssets;
  }

  public HealthCheckResponse netWorth(BigDecimal netWorth) {
    this.netWorth = netWorth;
    return this;
  }

   /**
   * Net worth, calculated as total_assets - total_liabilities.
   * @return netWorth
  **/
  @ApiModelProperty(value = "Net worth, calculated as total_assets - total_liabilities.")
  public BigDecimal getNetWorth() {
    return netWorth;
  }

  public void setNetWorth(BigDecimal netWorth) {
    this.netWorth = netWorth;
  }

  public HealthCheckResponse grossMonthlyIncome(BigDecimal grossMonthlyIncome) {
    this.grossMonthlyIncome = grossMonthlyIncome;
    return this;
  }

   /**
   * Gross monthly income, calculated as gross_annual_income / 12.
   * @return grossMonthlyIncome
  **/
  @ApiModelProperty(value = "Gross monthly income, calculated as gross_annual_income / 12.")
  public BigDecimal getGrossMonthlyIncome() {
    return grossMonthlyIncome;
  }

  public void setGrossMonthlyIncome(BigDecimal grossMonthlyIncome) {
    this.grossMonthlyIncome = grossMonthlyIncome;
  }

  public HealthCheckResponse monthlySurplus(BigDecimal monthlySurplus) {
    this.monthlySurplus = monthlySurplus;
    return this;
  }

   /**
   * Net monthly surplus, calculated as net_monthly_income - monthly_expenses.
   * @return monthlySurplus
  **/
  @ApiModelProperty(value = "Net monthly surplus, calculated as net_monthly_income - monthly_expenses.")
  public BigDecimal getMonthlySurplus() {
    return monthlySurplus;
  }

  public void setMonthlySurplus(BigDecimal monthlySurplus) {
    this.monthlySurplus = monthlySurplus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthCheckResponse healthCheckResponse = (HealthCheckResponse) o;
    return Objects.equals(this.liquidityRatioExpenses, healthCheckResponse.liquidityRatioExpenses) &&
        Objects.equals(this.liquidityRatioLiabilities, healthCheckResponse.liquidityRatioLiabilities) &&
        Objects.equals(this.currentRatio, healthCheckResponse.currentRatio) &&
        Objects.equals(this.assetAllocationRatio, healthCheckResponse.assetAllocationRatio) &&
        Objects.equals(this.savingsRatioGross, healthCheckResponse.savingsRatioGross) &&
        Objects.equals(this.savingsRatioNet, healthCheckResponse.savingsRatioNet) &&
        Objects.equals(this.totalAssets, healthCheckResponse.totalAssets) &&
        Objects.equals(this.netWorth, healthCheckResponse.netWorth) &&
        Objects.equals(this.grossMonthlyIncome, healthCheckResponse.grossMonthlyIncome) &&
        Objects.equals(this.monthlySurplus, healthCheckResponse.monthlySurplus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liquidityRatioExpenses, liquidityRatioLiabilities, currentRatio, assetAllocationRatio, savingsRatioGross, savingsRatioNet, totalAssets, netWorth, grossMonthlyIncome, monthlySurplus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthCheckResponse {\n");
    
    sb.append("    liquidityRatioExpenses: ").append(toIndentedString(liquidityRatioExpenses)).append("\n");
    sb.append("    liquidityRatioLiabilities: ").append(toIndentedString(liquidityRatioLiabilities)).append("\n");
    sb.append("    currentRatio: ").append(toIndentedString(currentRatio)).append("\n");
    sb.append("    assetAllocationRatio: ").append(toIndentedString(assetAllocationRatio)).append("\n");
    sb.append("    savingsRatioGross: ").append(toIndentedString(savingsRatioGross)).append("\n");
    sb.append("    savingsRatioNet: ").append(toIndentedString(savingsRatioNet)).append("\n");
    sb.append("    totalAssets: ").append(toIndentedString(totalAssets)).append("\n");
    sb.append("    netWorth: ").append(toIndentedString(netWorth)).append("\n");
    sb.append("    grossMonthlyIncome: ").append(toIndentedString(grossMonthlyIncome)).append("\n");
    sb.append("    monthlySurplus: ").append(toIndentedString(monthlySurplus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

