<?php
/**
 * AnnuityDepositScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\proton
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\proton;

/**
 * AnnuityDepositScheduleTest Class Doc Comment
 *
 * @category    Class
 * @description AnnuityDepositSchedule
 * @package     com\hydrogen\proton
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnnuityDepositScheduleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnnuityDepositSchedule"
     */
    public function testAnnuityDepositSchedule()
    {
    }

    /**
     * Test attribute "deposit_amount"
     */
    public function testPropertyDepositAmount()
    {
    }

    /**
     * Test attribute "deposit_frequency_interval"
     */
    public function testPropertyDepositFrequencyInterval()
    {
    }

    /**
     * Test attribute "adjust_deposit_for_inflation"
     */
    public function testPropertyAdjustDepositForInflation()
    {
    }
}
