<?php
/**
 * EducationCalculatorAnnualCostRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\proton
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\proton;

/**
 * EducationCalculatorAnnualCostRequestTest Class Doc Comment
 *
 * @category    Class
 * @description EducationCalculatorAnnualCostRequest
 * @package     com\hydrogen\proton
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EducationCalculatorAnnualCostRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EducationCalculatorAnnualCostRequest"
     */
    public function testEducationCalculatorAnnualCostRequest()
    {
    }

    /**
     * Test attribute "education_inflation_rate"
     */
    public function testPropertyEducationInflationRate()
    {
    }

    /**
     * Test attribute "decumulation_horizon"
     */
    public function testPropertyDecumulationHorizon()
    {
    }

    /**
     * Test attribute "accumulation_horizon"
     */
    public function testPropertyAccumulationHorizon()
    {
    }

    /**
     * Test attribute "account_ids"
     */
    public function testPropertyAccountIds()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "general_inflation_rate"
     */
    public function testPropertyGeneralInflationRate()
    {
    }

    /**
     * Test attribute "portfolio_return"
     */
    public function testPropertyPortfolioReturn()
    {
    }

    /**
     * Test attribute "deposit_schedule"
     */
    public function testPropertyDepositSchedule()
    {
    }

    /**
     * Test attribute "initial_balance"
     */
    public function testPropertyInitialBalance()
    {
    }

    /**
     * Test attribute "percent_of_costs_covered"
     */
    public function testPropertyPercentOfCostsCovered()
    {
    }

    /**
     * Test attribute "aggregation_account_ids"
     */
    public function testPropertyAggregationAccountIds()
    {
    }
}
