<?php
/**
 * PurchaseCalculatorHorizonRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\proton
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.9.1
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\proton;

/**
 * PurchaseCalculatorHorizonRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseCalculatorHorizonRequest
 * @package     com\hydrogen\proton
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseCalculatorHorizonRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseCalculatorHorizonRequest"
     */
    public function testPurchaseCalculatorHorizonRequest()
    {
    }

    /**
     * Test attribute "account_ids"
     */
    public function testPropertyAccountIds()
    {
    }

    /**
     * Test attribute "investment_tax"
     */
    public function testPropertyInvestmentTax()
    {
    }

    /**
     * Test attribute "portfolio_return"
     */
    public function testPropertyPortfolioReturn()
    {
    }

    /**
     * Test attribute "deposit_schedule"
     */
    public function testPropertyDepositSchedule()
    {
    }

    /**
     * Test attribute "current_savings"
     */
    public function testPropertyCurrentSavings()
    {
    }

    /**
     * Test attribute "purchase_amount"
     */
    public function testPropertyPurchaseAmount()
    {
    }

    /**
     * Test attribute "inflation_rate"
     */
    public function testPropertyInflationRate()
    {
    }

    /**
     * Test attribute "aggregation_account_ids"
     */
    public function testPropertyAggregationAccountIds()
    {
    }
}
