<?php
/**
 * FundingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\nucleus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * OpenAPI spec version: 1.9.1
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\nucleus;

/**
 * FundingTest Class Doc Comment
 *
 * @category    Class
 * @description Funding Object
 * @package     com\hydrogen\nucleus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FundingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Funding"
     */
    public function testFunding()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "bank_link_id"
     */
    public function testPropertyBankLinkId()
    {
    }

    /**
     * Test attribute "business_id"
     */
    public function testPropertyBusinessId()
    {
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "frequency_unit"
     */
    public function testPropertyFrequencyUnit()
    {
    }

    /**
     * Test attribute "funding_status"
     */
    public function testPropertyFundingStatus()
    {
    }

    /**
     * Test attribute "funding_type"
     */
    public function testPropertyFundingType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "is_deposit"
     */
    public function testPropertyIsDeposit()
    {
    }

    /**
     * Test attribute "last_request_date"
     */
    public function testPropertyLastRequestDate()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "next_request_date"
     */
    public function testPropertyNextRequestDate()
    {
    }

    /**
     * Test attribute "portfolio_id"
     */
    public function testPropertyPortfolioId()
    {
    }

    /**
     * Test attribute "receiving_account_id"
     */
    public function testPropertyReceivingAccountId()
    {
    }

    /**
     * Test attribute "receiving_bank_link_id"
     */
    public function testPropertyReceivingBankLinkId()
    {
    }

    /**
     * Test attribute "receiving_portfolio_id"
     */
    public function testPropertyReceivingPortfolioId()
    {
    }

    /**
     * Test attribute "secondary_id"
     */
    public function testPropertySecondaryId()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "support_ticket_id"
     */
    public function testPropertySupportTicketId()
    {
    }

    /**
     * Test attribute "threshold_amount"
     */
    public function testPropertyThresholdAmount()
    {
    }

    /**
     * Test attribute "transfer_id"
     */
    public function testPropertyTransferId()
    {
    }

    /**
     * Test attribute "transfer_speed"
     */
    public function testPropertyTransferSpeed()
    {
    }

    /**
     * Test attribute "transfer_type"
     */
    public function testPropertyTransferType()
    {
    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {
    }
}
