<?php
/**
 * OverflowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\nucleus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * OpenAPI spec version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\nucleus;

/**
 * OverflowTest Class Doc Comment
 *
 * @category    Class
 * @description Overflow Object
 * @package     com\hydrogen\nucleus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OverflowTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Overflow"
     */
    public function testOverflow()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }

    /**
     * Test attribute "funding_requests"
     */
    public function testPropertyFundingRequests()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "overflow_setting_id"
     */
    public function testPropertyOverflowSettingId()
    {
    }

    /**
     * Test attribute "total_overflow_amount"
     */
    public function testPropertyTotalOverflowAmount()
    {
    }

    /**
     * Test attribute "update_balances"
     */
    public function testPropertyUpdateBalances()
    {
    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {
    }
}
