<?php
/**
 * CardTransactionAuthorizationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\proton\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.8.0
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\proton;

/**
 * CardTransactionAuthorizationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CardTransactionAuthorizationRequest
 * @package     com\hydrogen\proton\
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardTransactionAuthorizationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardTransactionAuthorizationRequest"
     */
    public function testCardTransactionAuthorizationRequest()
    {
    }

    /**
     * Test attribute "merchant"
     */
    public function testPropertyMerchant()
    {
    }

    /**
     * Test attribute "partial_auth"
     */
    public function testPropertyPartialAuth()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "merchant_category_code"
     */
    public function testPropertyMerchantCategoryCode()
    {
    }

    /**
     * Test attribute "cleanse_data"
     */
    public function testPropertyCleanseData()
    {
    }

    /**
     * Test attribute "auth_type"
     */
    public function testPropertyAuthType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "transaction_type"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
    }

    /**
     * Test attribute "merchant_category"
     */
    public function testPropertyMerchantCategory()
    {
    }
}
