# coding: utf-8

"""
    Hydrogen Nucleus API

    The Hydrogen Nucleus API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@hydrogenplatform.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.page_feature_track import PageFeatureTrack  # noqa: E501
from nucleus_api.rest import ApiException


class TestPageFeatureTrack(unittest.TestCase):
    """PageFeatureTrack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageFeatureTrack(self):
        """Test PageFeatureTrack"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.page_feature_track.PageFeatureTrack()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
