# coding: utf-8

"""
    Hydrogen Nucleus API

    The Hydrogen Nucleus API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@hydrogenplatform.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.line_items import LineItems  # noqa: E501
from nucleus_api.rest import ApiException


class TestLineItems(unittest.TestCase):
    """LineItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLineItems(self):
        """Test LineItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.line_items.LineItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
