/**
 * Hydrogen Atom API
 * The Hydrogen Atom API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AggregationAccountTransactionPayload', 'model/AggregationAccountTransactionPayloadBankCredit', 'model/AggregationAccountTransactionPayloadInvestment', 'model/SecondaryId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AggregationAccountTransactionPayload'), require('./AggregationAccountTransactionPayloadBankCredit'), require('./AggregationAccountTransactionPayloadInvestment'), require('./SecondaryId'));
  } else {
    // Browser globals (root is window)
    if (!root.atom_api) {
      root.atom_api = {};
    }
    root.atom_api.CreateAggregationAccountTransactionResponse = factory(root.atom_api.ApiClient, root.atom_api.AggregationAccountTransactionPayload, root.atom_api.AggregationAccountTransactionPayloadBankCredit, root.atom_api.AggregationAccountTransactionPayloadInvestment, root.atom_api.SecondaryId);
  }
}(this, function(ApiClient, AggregationAccountTransactionPayload, AggregationAccountTransactionPayloadBankCredit, AggregationAccountTransactionPayloadInvestment, SecondaryId) {
  'use strict';




  /**
   * The CreateAggregationAccountTransactionResponse model module.
   * @module model/CreateAggregationAccountTransactionResponse
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>CreateAggregationAccountTransactionResponse</code>.
   * @alias module:model/CreateAggregationAccountTransactionResponse
   * @class
   * @implements module:model/AggregationAccountTransactionPayload
   * @param aggregationAccountId {String} The ID of the aggregation account to which the transaction record belongs
   * @param currencyCode {String} Alphabetic currency code for the currency of the transaction, limited to 3 characters
   * @param transactionDate {String} The date the transaction took place
   */
  var exports = function(aggregationAccountId, currencyCode, transactionDate) {
    var _this = this;

    AggregationAccountTransactionPayload.call(_this, aggregationAccountId, currencyCode, transactionDate);


  };

  /**
   * Constructs a <code>CreateAggregationAccountTransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAggregationAccountTransactionResponse} obj Optional instance to populate.
   * @return {module:model/CreateAggregationAccountTransactionResponse} The populated <code>CreateAggregationAccountTransactionResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      AggregationAccountTransactionPayload.constructFromObject(data, obj);
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('create_date')) {
        obj['create_date'] = ApiClient.convertToType(data['create_date'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of the aggregation account transaction
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Datetime the aggregation account transaction was created
   * @member {String} create_date
   */
  exports.prototype['create_date'] = undefined;

  // Implement AggregationAccountTransactionPayload interface:
  /**
   * The ID of the aggregation account to which the transaction record belongs
   * @member {String} aggregation_account_id
   */
exports.prototype['aggregation_account_id'] = undefined;

  /**
   * Alphabetic currency code for the currency of the transaction, limited to 3 characters
   * @member {String} currency_code
   */
exports.prototype['currency_code'] = undefined;

  /**
   * The date the transaction took place
   * @member {String} transaction_date
   */
exports.prototype['transaction_date'] = undefined;

  /**
   * @member {module:model/AggregationAccountTransactionPayloadBankCredit} bank_credit
   */
exports.prototype['bank_credit'] = undefined;

  /**
   * @member {module:model/AggregationAccountTransactionPayloadInvestment} investment
   */
exports.prototype['investment'] = undefined;

  /**
   * Indicates if this transaction will be excluded from any spending or income analysis done in Proton tools. Defaults to “false” which indicates it will not be excluded from Proton analyses
   * @member {Boolean} is_excluded_analysis
   */
exports.prototype['is_excluded_analysis'] = undefined;

  /**
   * @member {module:model/SecondaryId} secondary_id
   */
exports.prototype['secondary_id'] = undefined;

  /**
   * Custom information associated with the aggregation account transaction in the format key:value
   * @member {Object} metadata
   */
exports.prototype['metadata'] = undefined;



  return exports;
}));


