# coding: utf-8

"""
    Hydrogen Atom API

    The Hydrogen Atom API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@hydrogenplatform.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import atom_api
from atom_api.models.change_model_composition_response_inner import ChangeModelCompositionResponseInner  # noqa: E501
from atom_api.rest import ApiException


class TestChangeModelCompositionResponseInner(unittest.TestCase):
    """ChangeModelCompositionResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeModelCompositionResponseInner(self):
        """Test ChangeModelCompositionResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = atom_api.models.change_model_composition_response_inner.ChangeModelCompositionResponseInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
