# coding: utf-8

"""
    Hydrogen Atom API

    The Hydrogen Atom API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: info@hydrogenplatform.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import atom_api
from atom_api.models.create_node_response import CreateNodeResponse  # noqa: E501
from atom_api.rest import ApiException


class TestCreateNodeResponse(unittest.TestCase):
    """CreateNodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateNodeResponse(self):
        """Test CreateNodeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = atom_api.models.create_node_response.CreateNodeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
