/*
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * API version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package proton_api

type CustomerAnalysisRequest struct {
	CurrencyCode        string   `json:"currency_code,omitempty"`
	ClientId            string   `json:"client_id,omitempty"`
	ResponseLimit       int32    `json:"response_limit,omitempty"`
	EndDate             string   `json:"end_date,omitempty"`
	BenchmarkEndDate    string   `json:"benchmark_end_date,omitempty"`
	CurrencyConversion  string   `json:"currency_conversion,omitempty"`
	StartDate           string   `json:"start_date,omitempty"`
	CustomerIds         []string `json:"customer_ids,omitempty"`
	BusinessId          string   `json:"business_id,omitempty"`
	BenchmarkStartDate  string   `json:"benchmark_start_date,omitempty"`
	OnlyActiveCustomers bool     `json:"only_active_customers,omitempty"`
}
