/*
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * API version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package proton_api

type CardLimitCheckRequest struct {
	CurrencyCode           string   `json:"currency_code"`
	ClientId               string   `json:"client_id"`
	AsOfDate               string   `json:"as_of_date,omitempty"`
	TransactionStatusScope []string `json:"transaction_status_scope,omitempty"`
	CreateLog              bool     `json:"create_log,omitempty"`
}
