/*
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * API version: 1.9.4
 * Contact: info@hydrogenplatform.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nucleus_api


type Answer struct {
	CreateDate string `json:"create_date,omitempty"`
	Id         string    `json:"id,omitempty"`
	// image
	Image string `json:"image,omitempty"`
	// isDefault
	IsDefault bool `json:"is_default,omitempty"`
	// label
	Label string `json:"label,omitempty"`
	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`
	// orderIndex
	OrderIndex string    `json:"order_index,omitempty"`
	Question   *Question `json:"question,omitempty"`
	// questionId
	QuestionId  string    `json:"question_id,omitempty"`
	SecondaryId string    `json:"secondary_id,omitempty"`
	Tooltip     string    `json:"tooltip,omitempty"`
	UpdateDate  string `json:"update_date,omitempty"`
	// value
	Value string `json:"value"`
	// weight
	Weight float64 `json:"weight,omitempty"`
}
