=begin
#Hydrogen Electron API

#The Hydrogen Electron API

OpenAPI spec version: 1.3.1
Contact: info@hydrogenplatform.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ElectronApi::AchCardRequestCO
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AchCardRequestCO' do
  before do
    # run before each test
    @instance = ElectronApi::AchCardRequestCO.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AchCardRequestCO' do
    it 'should create an instance of AchCardRequestCO' do
      expect(@instance).to be_instance_of(ElectronApi::AchCardRequestCO)
    end
  end
  describe 'test attribute "nucleus_funding_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
