/*
 * Hydrogen Molecule API
 * The Hydrogen Molecule API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@hydrogenplatform.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TokenRestrictionCreatePayload
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-11T18:23:25.119-04:00")
public class TokenRestrictionCreatePayload {
  @SerializedName("type")
  private String type = null;

  @SerializedName("value")
  private String value = null;

  public TokenRestrictionCreatePayload type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the token restriction.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the token restriction.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public TokenRestrictionCreatePayload value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value assigned for the restriction
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The value assigned for the restriction")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenRestrictionCreatePayload tokenRestrictionCreatePayload = (TokenRestrictionCreatePayload) o;
    return Objects.equals(this.type, tokenRestrictionCreatePayload.type) &&
        Objects.equals(this.value, tokenRestrictionCreatePayload.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenRestrictionCreatePayload {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

