<?php
/**
 * CampaignPlanRateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen\nucleus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Nucleus API
 *
 * The Hydrogen Nucleus API
 *
 * OpenAPI spec version: 1.8.0
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen\nucleus;

/**
 * CampaignPlanRateTest Class Doc Comment
 *
 * @category    Class
 * @description CampaignPlanRate Object
 * @package     com\hydrogen\nucleus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignPlanRateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignPlanRate"
     */
    public function testCampaignPlanRate()
    {
    }

    /**
     * Test attribute "max_asset"
     */
    public function testPropertyMaxAsset()
    {
    }

    /**
     * Test attribute "min_asset"
     */
    public function testPropertyMinAsset()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }
}
