<?php
/**
 * NotificationSettingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com\hydrogen
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydrogen Atom API
 *
 * The Hydrogen Atom API
 *
 * OpenAPI spec version: 1.7.0
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com\hydrogen;

/**
 * NotificationSettingTest Class Doc Comment
 *
 * @category    Class
 * @description Notification Setting Object
 * @package     com\hydrogen
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationSettingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NotificationSetting"
     */
    public function testNotificationSetting()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "frequency_unit"
     */
    public function testPropertyFrequencyUnit()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_receive"
     */
    public function testPropertyIsReceive()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "notification_id"
     */
    public function testPropertyNotificationId()
    {
    }

    /**
     * Test attribute "secondary_id"
     */
    public function testPropertySecondaryId()
    {
    }

    /**
     * Test attribute "threshold_value"
     */
    public function testPropertyThresholdValue()
    {
    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {
    }
}
