/* 
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Proton.Api;
using Proton.ModelEntity;
using Proton.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Proton.Test
{
    /// <summary>
    ///  Class for testing AnnuityCalculatorAnnuityAmountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnnuityCalculatorAnnuityAmountRequestTests
    {
        // TODO uncomment below to declare an instance variable for AnnuityCalculatorAnnuityAmountRequest
        //private AnnuityCalculatorAnnuityAmountRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnnuityCalculatorAnnuityAmountRequest
            //instance = new AnnuityCalculatorAnnuityAmountRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnnuityCalculatorAnnuityAmountRequest
        /// </summary>
        [Test]
        public void AnnuityCalculatorAnnuityAmountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnnuityCalculatorAnnuityAmountRequest
            //Assert.IsInstanceOfType<AnnuityCalculatorAnnuityAmountRequest> (instance, "variable 'instance' is a AnnuityCalculatorAnnuityAmountRequest");
        }


        /// <summary>
        /// Test the property 'InflationRate'
        /// </summary>
        [Test]
        public void InflationRateTest()
        {
            // TODO unit test for the property 'InflationRate'
        }
        /// <summary>
        /// Test the property 'DecumulationHorizon'
        /// </summary>
        [Test]
        public void DecumulationHorizonTest()
        {
            // TODO unit test for the property 'DecumulationHorizon'
        }
        /// <summary>
        /// Test the property 'AccountIds'
        /// </summary>
        [Test]
        public void AccountIdsTest()
        {
            // TODO unit test for the property 'AccountIds'
        }
        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Test]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }
        /// <summary>
        /// Test the property 'AccumulationHorizon'
        /// </summary>
        [Test]
        public void AccumulationHorizonTest()
        {
            // TODO unit test for the property 'AccumulationHorizon'
        }
        /// <summary>
        /// Test the property 'AnnuityAmount'
        /// </summary>
        [Test]
        public void AnnuityAmountTest()
        {
            // TODO unit test for the property 'AnnuityAmount'
        }
        /// <summary>
        /// Test the property 'PortfolioReturn'
        /// </summary>
        [Test]
        public void PortfolioReturnTest()
        {
            // TODO unit test for the property 'PortfolioReturn'
        }
        /// <summary>
        /// Test the property 'DepositSchedule'
        /// </summary>
        [Test]
        public void DepositScheduleTest()
        {
            // TODO unit test for the property 'DepositSchedule'
        }
        /// <summary>
        /// Test the property 'AnnuityFrequencyInterval'
        /// </summary>
        [Test]
        public void AnnuityFrequencyIntervalTest()
        {
            // TODO unit test for the property 'AnnuityFrequencyInterval'
        }
        /// <summary>
        /// Test the property 'InitialBalance'
        /// </summary>
        [Test]
        public void InitialBalanceTest()
        {
            // TODO unit test for the property 'InitialBalance'
        }
        /// <summary>
        /// Test the property 'AggregationAccountIds'
        /// </summary>
        [Test]
        public void AggregationAccountIdsTest()
        {
            // TODO unit test for the property 'AggregationAccountIds'
        }
        /// <summary>
        /// Test the property 'CreateLog'
        /// </summary>
        [Test]
        public void CreateLogTest()
        {
            // TODO unit test for the property 'CreateLog'
        }

    }

}
