/* 
 * Hydrogen Proton API
 *
 * Financial engineering module of Hydrogen Atom
 *
 * OpenAPI spec version: 1.9.2
 * Contact: info@hydrogenplatform.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Proton.Api;
using Proton.ModelEntity;
using Proton.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Proton.Test
{
    /// <summary>
    ///  Class for testing RiskAllocationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RiskAllocationRequestTests
    {
        // TODO uncomment below to declare an instance variable for RiskAllocationRequest
        //private RiskAllocationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RiskAllocationRequest
            //instance = new RiskAllocationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RiskAllocationRequest
        /// </summary>
        [Test]
        public void RiskAllocationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RiskAllocationRequest
            //Assert.IsInstanceOfType<RiskAllocationRequest> (instance, "variable 'instance' is a RiskAllocationRequest");
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'AllocationMethod'
        /// </summary>
        [Test]
        public void AllocationMethodTest()
        {
            // TODO unit test for the property 'AllocationMethod'
        }
        /// <summary>
        /// Test the property 'OptConfig'
        /// </summary>
        [Test]
        public void OptConfigTest()
        {
            // TODO unit test for the property 'OptConfig'
        }
        /// <summary>
        /// Test the property 'MarketDataSource'
        /// </summary>
        [Test]
        public void MarketDataSourceTest()
        {
            // TODO unit test for the property 'MarketDataSource'
        }
        /// <summary>
        /// Test the property 'RiskScore'
        /// </summary>
        [Test]
        public void RiskScoreTest()
        {
            // TODO unit test for the property 'RiskScore'
        }
        /// <summary>
        /// Test the property 'UseProxyData'
        /// </summary>
        [Test]
        public void UseProxyDataTest()
        {
            // TODO unit test for the property 'UseProxyData'
        }
        /// <summary>
        /// Test the property 'Allocations'
        /// </summary>
        [Test]
        public void AllocationsTest()
        {
            // TODO unit test for the property 'Allocations'
        }

    }

}
